version: 0.1
phases:
  install:
    commands:
      #- npm install time
      #- aws cloudformation package --template-file samTemplate.yaml --s3-bucket bucket-name --output-template-file NewSamTemplate.yaml
      #CONFIG ENV
      - yum install gcc gcc-c++ make wget -y
      - yum install autoconf aclocal automake -y
      - yum install libtool zip -y
      - yum install libjpeg-devel libpng-devel libtiff-devel zlib-devel -y
      - yum install git -y
      - yum install python-devel libusbx-devel systemd-devel -y
      - chmod 755 build.sh
      #BUILD
      - ./build.sh
artifacts:
  files:
    - '**/*.zip'
  discard-paths: no
